import mongoose from "mongoose";
import autoIncrement from "../utils/autoIncrement.js";

// Boost model for tracking property boost payments
const boostSchema = new mongoose.Schema(
    {
        boostId: {
            type: String,
            unique: true,
            // Auto-generated by pre-save hook
        },
        property: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Property",
            required: true,
        },
        landlord: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            // Optional until auth is implemented
        },
        amount: {
            type: Number,
            required: true,
        },
        duration: {
            type: Number, // Duration in days
            required: true,
        },
        startDate: {
            type: Date,
            default: Date.now,
        },
        endDate: {
            type: Date,
            required: true,
        },
        status: {
            type: String,
            enum: ["active", "expired", "cancelled"],
            default: "active",
        },
        paymentMethod: {
            type: String,
            default: "card",
        },
        // Mock payment details
        paymentReference: {
            type: String,
            default: function () {
                return "PAY-" + Math.random().toString(36).substr(2, 9).toUpperCase();
            },
        },
    },
    {
        timestamps: true,
    }
);

// For generation of Boost ID
boostSchema.plugin(autoIncrement, {
    model: "Boost",
    field: "boostId",
    prefix: "BOOST-",
    padLength: 6,
});

// Method to check if boost is still active
boostSchema.methods.isActive = function () {
    return this.status === "active" && new Date() < this.endDate;
};

const Boost = mongoose.model("Boost", boostSchema);

export default Boost;
