import mongoose from "mongoose";
import autoIncrement from "../utils/autoIncrement.js";

// Main property schema
const propertySchema = new mongoose.Schema(
  {
    propertyId: {
      type: String,
      unique: true,
      // Auto-generated by pre-save hook, so not required
    },
    title: {
      type: String,
      required: true,
    },
    description: {
      type: String,
      required: true,
    },
    type: {
      type: String,
      enum: ["house", "apartment", "land", "commercial"],
      default: "house",
    },
    address: {
      type: {
        // Define the structure *inside* a 'type' property
        street: { type: String, required: true },
        city: { type: String, required: true },
        state: { type: String, required: true },
        country: { type: String, required: true },
      },
      required: true, // This makes the entire 'address' field required
    },

    landlord: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: false, // Made optional for testing until auth is implemented
    },

    averageRating: {
      type: Number,
      default: 0,
    },
    images: {
      type: [String],
      required: true,
    },

    price: {
      type: Number, // Rent or sale
      required: true,
    },

    // New fields for property details
    beds: {
      type: Number,
      default: 0,
    },
    baths: {
      type: Number,
      default: 0,
    },
    sqft: {
      type: String,
    },

    status: {
      type: String,
      enum: ["available", "sold", "rented", "pending", "bidding"],
      default: "available",
    },
    
    // Listing type - determines if property is for sale or rent
    listingType: {
      type: String,
      enum: ["sell", "rent"],
      default: "rent",
    },
    
    // Starting/asking price for sell properties (base for bidding)
    startingPrice: {
      type: Number,
      required: function() { return this.listingType === "sell"; },
    },
    
    // Current price - for rent: monthly rent; for sell: current highest bid or asking price
    currentPrice: {
      type: Number,
    },
    
    // Whether the property accepts bids (only applicable for sell listings)
    isBiddable: {
      type: Boolean,
      default: false,
    },
    priority: {
      type: Number,
      default: 1, // Boosted => higher value = higher list priority
    },
    reviews: [
      {
        user: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "User",
          required: true,
        },
        rating: {
          type: Number,
          min: 1,
          max: 5,
          required: true,
        },
        comment: {
          type: String,
        },
        createdAt: {
          type: Date,
          default: Date.now,
        },
      },
    ],
  },
  {
    timestamps: true, // createdAt, updatedAt
  }
);
// For generation of Property ID
propertySchema.plugin(autoIncrement, {
  model: "Property",
  field: "propertyId",
  prefix: "PROP-",
  padLength: 6,
});

// Creation of the model based on above schema
const Property = mongoose.model("Property", propertySchema);

export default Property;
