import mongoose from "mongoose";
import autoIncrement from "../utils/autoIncrement.js";

const propertyBidSchema = new mongoose.Schema(
    {
        bidId: {
            type: String,
            unique: true,
            // Auto-generated by plugin
        },

        bidAmount: {
            type: Number,
            required: true,
            min: [1, "Bid amount must be positive"],
        },

        bidder: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: true,
        },

        property: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Property",
            required: true,
        },

        status: {
            type: String,
            enum: ["pending", "accepted", "rejected", "outbid"],
            default: "pending",
        },

        // Optional message from bidder to landlord
        message: {
            type: String,
            maxlength: 500,
        },
    },
    { timestamps: true }
);

// Indexes for efficient queries
propertyBidSchema.index({ property: 1, bidder: 1 });
propertyBidSchema.index({ property: 1, status: 1 });
propertyBidSchema.index({ bidder: 1, status: 1 });

propertyBidSchema.plugin(autoIncrement, {
    model: "PropertyBid",
    field: "bidId",
    prefix: "BID-",
    padLength: 6,
});

const PropertyBid = mongoose.model("PropertyBid", propertyBidSchema);

export default PropertyBid;
